### ISSUE TITLE
action fails with v3.7.2 sops release on ubuntu-latest runner

### ISSUE THREAD

**Issue by jleoirab** [mdgreenwald/mozilla-sops-action#105]
Hello, 
I started noticing after the latest sops release that this GHA begins to fail with the following error
```
line 1: /opt/hostedtoolcache/sops/3.7.2/x64/sops: cannot execute binary file: Exec format error
```

This seems related to this release including arm64 artifacts separately as well?

This is how I've been installing the action:

```yaml
- name: install sops
      uses: mdgreenwald/mozilla-sops-action@v1.1.0
      id: install
```

When I pinned the sops version to the previous release 3.7.1, it started working well again.

```yaml
- name: install sops
      uses: mdgreenwald/mozilla-sops-action@v1.1.0
      with:
        version: '3.7.1'
      id: install
```

GHA Runner: ubuntu-latest

Thanks
